name: Linux Build Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:

  linux:
    name: Build Custom Telegram Linux
    runs-on: ubuntu-latest

    env:
      UPLOAD_ARTIFACT: "true"
      IMAGE_TAG: tdesktop:centos_env
      ARTIFACT_NAME: "Telegram-Custom-Linux"

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Clone official Telegram Desktop v7.0.5.
        run: |
          git clone --recursive --branch v7.0.5 https://github.com/telegramdesktop/tdesktop.git tdesktop-src
          cp -r tdesktop-src/* .
          cp -r tdesktop-src/.* . 2>/dev/null || true
          rm -rf tdesktop-src

      - name: Apply Custom Features Patch.
        run: |
          git config user.name "Javad"
          git config user.email "javad@local.dev"
          git apply --3way custom_features.patch || git am --3way < custom_features.patch || git apply --reject --ignore-whitespace custom_features.patch

      - name: Set up API keys in config.h.
        run: |
          sed -i 's/#error You are required to provide API_ID and API_HASH./constexpr auto ApiId = 29579556; constexpr auto ApiHash = "351a588e027c04b1b5a1c2b28cbd9cfd";/' Telegram/SourceFiles/config.h

      - name: First set up.
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -
          curl -sSL https://github.com/ccache/ccache/releases/download/v4.13.6/ccache-4.13.6-linux-x86_64-glibc.tar.xz \
          | sudo tar xJ -C /usr/local/bin --strip-components=1 ccache-4.13.6-linux-x86_64-glibc/ccache
          echo "CCACHE_DIR=$RUNNER_TEMP/.tdesktop-cache" >> $GITHUB_ENV
          cd Telegram/build/docker/centos_env
          poetry install
          DOCKERFILE=$(DEBUG= LTO= poetry run gen_dockerfile)
          echo "$DOCKERFILE" > Dockerfile
          rm -rf __pycache__

      - name: Free up disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v4

      - name: Build Docker container.
        uses: docker/build-push-action@v7
        with:
          context: Telegram/build/docker/centos_env
          load: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Build Telegram Desktop.
        run: |
          ccache -z
          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          -v ${{ env.CCACHE_DIR }}:/var/cache/ccache \
          -e CONFIG=Debug \
          -e CCACHE_SLOPPINESS=pch_defines,time_macros \
          $IMAGE_TAG \
          env -u CCACHE_DISABLE /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Debug \
          -D CMAKE_C_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D CMAKE_CXX_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D CMAKE_COMPILE_WARNING_AS_ERROR=OFF \
          -D TDESKTOP_API_ID=29579556 \
          -D TDESKTOP_API_HASH=351a588e027c04b1b5a1c2b28cbd9cfd \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF

      - name: Move artifact.
        run: |
          cd out/Debug
          mkdir artifact
          mv Telegram artifact/

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/Debug/artifact/
